### ISSUE TITLE
views should not be labeled views

### ISSUE THREAD

**Issue by Bananeweizen** [snyk/snyk-eclipse-plugin#5]
General UI rule in Eclipse: don't use labels that contain the kind of object you are looking at. With that in mind, please change
* "Snyk View" -> "Snyk" or "Snyk Vulnerabilities" or "Snyk something"
* "Snyk Preferences" -> "Snyk"

**Comment by bmvermeer** [comment]
Thanks for reporting.
We will take this into account probably at the next major update.

**Comment by bmvermeer** [comment]
Solved
