### ISSUE TITLE
Latest version of Eclipse plugin doesn't install CLI

### ISSUE THREAD

**Issue by arosinijc** [snyk/snyk-eclipse-plugin#57]
When trying to install from the Eclipse Marketplace the latest version of the plugin, it installs successfully, but when I restart Eclipse I get an error that `Host name cannot be null`. I also see in the Snyk view that I am missing `~/.snyk/snyk-macos` and that the Snyk operations cannot be run due to a missing `~/.snyk/snyk-ls`.

The host name cannot be null error has a stack trace that points to https://github.com/snyk/snyk-eclipse-plugin/blob/main/plugin/src/main/java/io/snyk/eclipse/plugin/utils/CliDownloader.java#L86. I see this was modified in https://github.com/snyk/snyk-eclipse-plugin/commit/9e7095c0b2f463da438efa839942f834ecf9e92c.

I tried downloading the CLI manually (using brew) but that didn't create the needed configuration or language server in a way that Eclipse recognized, and I didn't see anything that looked like it could be pointed to.

I then tried manually downloading the previous release of the plugin and installing that and it worked. I am using MacOS v12.4 and I tried this with Eclipse 2022-06 and 2022-03.

I see in that CliDownloader class you are saying this will all be reworked soon, so maybe this is all moot and will be fixed soon.

**Comment by bastiandoetsch** [comment]
Hi @arosinijc, yes, the rework is under way (see current PRs). Still, this error should not happen, and I'm sorry you encountered it. I'll have a look, the fix looks easy.

**Comment by bastiandoetsch** [comment]
It's released to marketplace :)

**Comment by bastiandoetsch** [comment]
Same issue occurred for language server download - PR pending approval.
